// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/v1/common.proto (package goserver.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/common.proto.
 */
export const file_api_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChNhcGkvdjEvY29tbW9uLnByb3RvEg9nb3NlcnZlci5hcGkudjEiqAIKBFVzZXISDwoCaWQYASABKANCA+BBAxIVCgh1c2VybmFtZRgCIAEoCUID4EECEhIKBWVtYWlsGAMgASgJQgPgQQISFQoIbmlja25hbWUYBCABKAlCA+BBAhISCgVwaG9uZRgFIAEoCUID4EECEhEKBHJvbGUYBiABKAlCA+BBAxI8ChNwYXNzd29yZF9leHBpcmVzX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDEjMKCmNyZWF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgPgQQMSMwoKdXBkYXRlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCA+BBA0KyAQoTY29tLmdvc2VydmVyLmFwaS52MUILQ29tbW9uUHJvdG9QAVowZ2l0aHViLmNvbS9waXhiL2dvLXNlcnZlci9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDR0FYqgIPR29zZXJ2ZXIuQXBpLlYxygIPR29zZXJ2ZXJcQXBpXFYx4gIbR29zZXJ2ZXJcQXBpXFYxXEdQQk1ldGFkYXRh6gIRR29zZXJ2ZXI6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * @generated from message goserver.api.v1.User
 */
export type User = Message<"goserver.api.v1.User"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string nickname = 4;
   */
  nickname: string;

  /**
   * @generated from field: string phone = 5;
   */
  phone: string;

  /**
   * @generated from field: string role = 6;
   */
  role: string;

  /**
   * @generated from field: google.protobuf.Timestamp password_expires_at = 7;
   */
  passwordExpiresAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message goserver.api.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_api_v1_common, 0);

