// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/v1/instance_service.proto (package goserver.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "./common_pb";
import { file_api_v1_common } from "./common_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/instance_service.proto.
 */
export const file_api_v1_instance_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1hcGkvdjEvaW5zdGFuY2Vfc2VydmljZS5wcm90bxIPZ29zZXJ2ZXIuYXBpLnYxIlYKD0luc3RhbmNlUHJvZmlsZRIPCgd2ZXJzaW9uGAEgASgJEgwKBGRlbW8YAiABKAgSJAoFYWRtaW4YAyABKAsyFS5nb3NlcnZlci5hcGkudjEuVXNlciIbChlHZXRJbnN0YW5jZVByb2ZpbGVSZXF1ZXN0MpgBCg9JbnN0YW5jZVNlcnZpY2UShAEKEkdldEluc3RhbmNlUHJvZmlsZRIqLmdvc2VydmVyLmFwaS52MS5HZXRJbnN0YW5jZVByb2ZpbGVSZXF1ZXN0GiAuZ29zZXJ2ZXIuYXBpLnYxLkluc3RhbmNlUHJvZmlsZSIggtPkkwIaEhgvYXBpL3YxL2luc3RhbmNlL3Byb2ZpbGVCuwEKE2NvbS5nb3NlcnZlci5hcGkudjFCFEluc3RhbmNlU2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vcGl4Yi9nby1zZXJ2ZXIvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA0dBWKoCD0dvc2VydmVyLkFwaS5WMcoCD0dvc2VydmVyXEFwaVxWMeICG0dvc2VydmVyXEFwaVxWMVxHUEJNZXRhZGF0YeoCEUdvc2VydmVyOjpBcGk6OlYxYgZwcm90bzM", [file_api_v1_common, file_google_api_annotations]);

/**
 * Instance profile message containing basic instance information.
 *
 * @generated from message goserver.api.v1.InstanceProfile
 */
export type InstanceProfile = Message<"goserver.api.v1.InstanceProfile"> & {
  /**
   * Version is the current version of instance.
   *
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * Demo indicates if the instance is in demo mode.
   *
   * @generated from field: bool demo = 2;
   */
  demo: boolean;

  /**
   * The first administrator who set up this instance.
   * When null, instance requires initial setup (creating the first admin account).
   *
   * @generated from field: goserver.api.v1.User admin = 3;
   */
  admin?: User;
};

/**
 * Describes the message goserver.api.v1.InstanceProfile.
 * Use `create(InstanceProfileSchema)` to create a new message.
 */
export const InstanceProfileSchema: GenMessage<InstanceProfile> = /*@__PURE__*/
  messageDesc(file_api_v1_instance_service, 0);

/**
 * Request for instance profile.
 *
 * @generated from message goserver.api.v1.GetInstanceProfileRequest
 */
export type GetInstanceProfileRequest = Message<"goserver.api.v1.GetInstanceProfileRequest"> & {
};

/**
 * Describes the message goserver.api.v1.GetInstanceProfileRequest.
 * Use `create(GetInstanceProfileRequestSchema)` to create a new message.
 */
export const GetInstanceProfileRequestSchema: GenMessage<GetInstanceProfileRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_instance_service, 1);

/**
 * @generated from service goserver.api.v1.InstanceService
 */
export const InstanceService: GenService<{
  /**
   * Gets the instance profile.
   *
   * @generated from rpc goserver.api.v1.InstanceService.GetInstanceProfile
   */
  getInstanceProfile: {
    methodKind: "unary";
    input: typeof GetInstanceProfileRequestSchema;
    output: typeof InstanceProfileSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_instance_service, 0);

