// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file store/instance_setting.proto (package goserver.store, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file store/instance_setting.proto.
 */
export const file_store_instance_setting: GenFile = /*@__PURE__*/
  fileDesc("ChxzdG9yZS9pbnN0YW5jZV9zZXR0aW5nLnByb3RvEg5nb3NlcnZlci5zdG9yZSKKAQoPSW5zdGFuY2VTZXR0aW5nEi8KA2tleRgBIAEoDjIiLmdvc2VydmVyLnN0b3JlLkluc3RhbmNlU2V0dGluZ0tleRI9Cg1iYXNpY19zZXR0aW5nGAIgASgLMiQuZ29zZXJ2ZXIuc3RvcmUuSW5zdGFuY2VCYXNpY1NldHRpbmdIAEIHCgV2YWx1ZSJCChRJbnN0YW5jZUJhc2ljU2V0dGluZxISCgpzZWNyZXRfa2V5GAEgASgJEhYKDnNjaGVtYV92ZXJzaW9uGAIgASgJKkUKEkluc3RhbmNlU2V0dGluZ0tleRIkCiBJTlNUQU5DRV9TRVRUSU5HX0tFWV9VTlNQRUNJRklFRBAAEgkKBUJBU0lDEAFCrgEKEmNvbS5nb3NlcnZlci5zdG9yZUIUSW5zdGFuY2VTZXR0aW5nUHJvdG9QAVopZ2l0aHViLmNvbS9waXhiL2dvLXNlcnZlci9wcm90by9nZW4vc3RvcmWiAgNHU1iqAg5Hb3NlcnZlci5TdG9yZcoCDkdvc2VydmVyXFN0b3Jl4gIaR29zZXJ2ZXJcU3RvcmVcR1BCTWV0YWRhdGHqAg9Hb3NlcnZlcjo6U3RvcmViBnByb3RvMw");

/**
 * @generated from message goserver.store.InstanceSetting
 */
export type InstanceSetting = Message<"goserver.store.InstanceSetting"> & {
  /**
   * @generated from field: goserver.store.InstanceSettingKey key = 1;
   */
  key: InstanceSettingKey;

  /**
   * @generated from oneof goserver.store.InstanceSetting.value
   */
  value: {
    /**
     * @generated from field: goserver.store.InstanceBasicSetting basic_setting = 2;
     */
    value: InstanceBasicSetting;
    case: "basicSetting";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message goserver.store.InstanceSetting.
 * Use `create(InstanceSettingSchema)` to create a new message.
 */
export const InstanceSettingSchema: GenMessage<InstanceSetting> = /*@__PURE__*/
  messageDesc(file_store_instance_setting, 0);

/**
 * @generated from message goserver.store.InstanceBasicSetting
 */
export type InstanceBasicSetting = Message<"goserver.store.InstanceBasicSetting"> & {
  /**
   * The secret key for instance. Mainly used for session management.
   *
   * @generated from field: string secret_key = 1;
   */
  secretKey: string;

  /**
   * The current schema version of database.
   *
   * @generated from field: string schema_version = 2;
   */
  schemaVersion: string;
};

/**
 * Describes the message goserver.store.InstanceBasicSetting.
 * Use `create(InstanceBasicSettingSchema)` to create a new message.
 */
export const InstanceBasicSettingSchema: GenMessage<InstanceBasicSetting> = /*@__PURE__*/
  messageDesc(file_store_instance_setting, 1);

/**
 * @generated from enum goserver.store.InstanceSettingKey
 */
export enum InstanceSettingKey {
  /**
   * @generated from enum value: INSTANCE_SETTING_KEY_UNSPECIFIED = 0;
   */
  INSTANCE_SETTING_KEY_UNSPECIFIED = 0,

  /**
   * BASIC is the key for basic settings.
   *
   * @generated from enum value: BASIC = 1;
   */
  BASIC = 1,
}

/**
 * Describes the enum goserver.store.InstanceSettingKey.
 */
export const InstanceSettingKeySchema: GenEnum<InstanceSettingKey> = /*@__PURE__*/
  enumDesc(file_store_instance_setting, 0);

